services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../public:/var/www/html
      - ../vendor:/var/www/vendor
      - ../config:/var/www/config
      - ../src:/var/www/src
      - ./.env:/var/www/.env
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../workers:/var/www/workers
      - ../config:/var/www/config
      - ../vendor:/var/www/vendor
      - ../src:/var/www/src
      - ./.env:/var/www/.env
    depends_on:
      - db
    command: sh /var/www/workers/docker-worker-entrypoint.sh
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "5432:5432"
    env_file:
      - .env
